# -*- coding: utf-8 -*-
"""DecisionTreeDrugClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDfuR1Biy-UMx0Etok0kU480LecBqsza
"""

#Import my libraries
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

#Downloading data from IBM Storage
!wget -O drug200.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv

#Read and show data
my_data = pd.read_csv("drug200.csv", delimiter=",")
my_data[0:50]

size = len(my_data[['Drug']])
size
x = my_data[['Age' , 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug']].values
x[0:5]

#Convert categorical to numerical values
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
x[:,1] = le_sex.transform(x[:,1]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
x[:,2] = le_BP.transform(x[:,2])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
x[:,3] = le_Chol.transform(x[:,3]) 

x[0:5]

from sklearn.model_selection import train_test_split
xtrain,ytrain,xtest,ytest = train_test_split(x, y, test_size = 0.3, random_state = 3)